#!/bin/bash
set -o errexit

[ $(id -u) -eq 0 ] && { echo "You should not run this as root user"; exit 1; }

sudo apt update -y && sudo apt install --yes --no-install-recommends curl gpg

### Install VSCodium repository
curl https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg \
  | sudo sudo gpg --yes --dearmor --output /etc/apt/keyrings/vscodium-archive-keyring.gpg

cat << EOF | sudo tee /etc/apt/sources.list.d/vscodium.sources
Types: deb
URIs: https://download.vscodium.com/debs
Suites: vscodium
Components: main
Architectures: amd64 arm64
Signed-by: /etc/apt/keyrings/vscodium-archive-keyring.gpg
EOF

### Install Mozilla Repostitory
curl https://packages.mozilla.org/apt/repo-signing-key.gpg \
  | sudo sudo gpg --yes --dearmor --output /etc/apt/keyrings/packages.mozilla.org.asc

cat << EOF | sudo tee /etc/apt/sources.list.d/mozilla.sources
Types: deb
URIs: https://packages.mozilla.org/apt
Suites: mozilla
Components: main
Architectures: amd64
Signed-by: /etc/apt/keyrings/packages.mozilla.org.asc
EOF

cat << EOF | sudo tee /etc/apt/preferences.d/mozilla
Package: *
Pin: origin packages.mozilla.org
Pin-Priority: 1000
EOF

### Install Kubernetes repository
curl -L https://pkgs.k8s.io/core:/stable:/v1.33/deb/Release.key \
  | sudo sudo gpg --yes --dearmor --output /etc/apt/keyrings/kubernetes-apt-keyring.gpg

cat << EOF | sudo tee /etc/apt/sources.list.d/kubernetes.sources
Types: deb
URIs: https://pkgs.k8s.io/core:/stable:/v1.33/deb/
Suites: /
Signed-By: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
EOF

### Install Helm repository
curl -L https://baltocdn.com/helm/signing.asc \
  | sudo sudo gpg --yes --dearmor --output /etc/apt/keyrings/helm.gpg

cat << EOF | sudo tee /etc/apt/sources.list.d/kubernetes.sources
Types: deb
URIs: https://baltocdn.com/helm/stable/debian/
Suites: all
Components: main
Signed-By: /etc/apt/keyrings/helm.gpg
EOF

### Install Docker repository
curl -L https://download.docker.com/linux/debian/gpg \
  | sudo sudo gpg --yes --dearmor --output /etc/apt/keyrings/docker.asc

cat << EOF | sudo tee /etc/apt/sources.list.d/docker.sources
Types: deb
URIs: https://download.docker.com/linux/debian
Suites: trixie
Components: stable
Signed-By: /etc/apt/keyrings/docker.asc
EOF

### Install DbBeaver repository
curl -L https://dbeaver.io/debs/dbeaver.gpg.key \
  | sudo gpg --yes --dearmor --output /etc/apt/keyrings/dbeaver.gpg.key

cat << EOF | sudo tee /etc/apt/sources.list.d/dbeaver.sources
Types: deb
URIs: https://dbeaver.io/debs/dbeaver-ce
Suites: /
Signed-By: /etc/apt/keyrings/dbeaver.gpg.key
EOF

### Install Lens repository
curl -fsSL https://downloads.k8slens.dev/keys/gpg \
  | sudo gpg --yes --dearmor --output /etc/apt/keyrings/lens.asc

cat << EOF | sudo tee /etc/apt/sources.list.d/lens.sources
Types: deb
URIs: https://downloads.k8slens.dev/apt/debian
Suites: stable
Components: main
Signed-By: /etc/apt/keyrings/lens.asc
EOF

### Install VirtualBox repository
curl -L https://www.virtualbox.org/download/oracle_vbox_2016.asc \
  | sudo gpg --yes --dearmor --output /etc/apt/keyrings/virtualbox.asc

cat << EOF | sudo tee /etc/apt/sources.list.d/virtualbox.sources
Types: deb
URIs: https://download.virtualbox.org/virtualbox/debian
Suites: trixie
Components: contrib non-free
Signed-By: /etc/apt/keyrings/virtualbox.asc
EOF

sudo apt-get update -y &&
sudo apt-get install --yes --no-install-recommends \
  gdm3 \
  gnome-shell \
  gnome-terminal \
  gnome-session \
  gnome-session-xsession \
  gnome-tweaks \
  gnome-remote-desktop \
  gnome-shell-extension-manager \
  gnome-shell-extension-blur-my-shell \
  gnome-shell-extension-drive-menu \
  gnome-shell-extension-appindicator \
  dconf-cli \
  nautilus-extension-gnome-terminal \
  libgnome-menu-3-dev \
  gir1.2-gmenu-3.0 \
  network-manager \
  network-manager-gnome \
  xserver-xorg-core \
  xserver-xorg-input-libinput \
  firefox-devedition \
  firefox-devedition-l10n-ru \
  thunderbird \
  thunderbird-l10n-ru \
  dbeaver-ce \
  docker-ce \
  docker-ce-cli \
  containerd.io \
  docker-buildx-plugin \
  docker-compose-plugin \
  codium \
  kubectl \
  helm \
  python3-venv \
  lens \
  pipx &&

[ -f /etc/network/interfaces ] && sudo mv /etc/network/interfaces /etc/network/interfaces.bak && sudo systemctl restart NetworkManager
[ -f ~/.config/dconf/user.keyfile ] && dconf load / < .config/dconf/user.keyfile
sudo usermod -aG docker $(id --user --name)

pipx ensurepath \
  && pipx install ansible-core \
  && pipx inject --include-apps ansible-core ansible-lint \
  && pipx inject ansible-core argcomplete \
  && sudo activate-global-python-argcomplete

CODIUM_EXTENSIONS=(ms-ceintl.vscode-language-pack-ru
redhat.vscode-yaml
beardedbear.beardedtheme
beardedbear.beardedicons
redhat.ansible
mads-hartmann.bash-ide-vscode
ms-azuretools.vscode-docker
ms-azuretools.vscode-containers
)

CODIUM_EXTERNAL_EXTENSIONS=(
  https://github.com/ipierre1/ansible-vault-vscode/releases/download/v1.0.12/ansible-vault-vscode-1.0.12.vsix
)

for ext in ${CODIUM_EXTENSIONS[@]}
do
    codium --install-extension $ext
done

for ext_url in ${CODIUM_EXTERNAL_EXTENSIONS[@]}
do
    [ ! -f "/tmp/$(basename $ext_url)" ] && curl --location $ext_url --output /tmp/$(basename $ext_url)
    codium --install-extension /tmp/$(basename $ext_url)
done

kubectl completion bash | sudo tee /etc/bash_completion.d/kubectl \
  && helm completion bash | sudo tee /etc/bash_completion.d/helm \
  && register-python-argcomplete --shell bash pipx | sudo tee /etc/bash_completion.d/pipx

sudo systemctl enable --now gdm3
